### ISSUE TITLE
Error during compilation, please comment

### ISSUE THREAD

**Issue by xxroot** [pjgowtham/recovery_device_xiaomi_ares#1]
I'm using
https://github.com/minimal-manifest-twrp/platform_manifest_twrp  Compile TWRP,
Compiling process, there is an error, do not know how to handle, please advise  
I do not know how to set this, Google search for this problem did not find the relevant solution  

code
```[ 99% 30324/30433] including out/soong/Android-twrp_ares.mk ...
FAILED: 
out/soong/Android-twrp_ares.mk: error: CtsJdwpTestCases: Installable device modu
le must have LOCAL_SOONG_DEX_JAR set 
In file included from build/make/core/main.mk:433:
In file included from out/soong/Android-twrp_ares.mk:15173:
build/make/core/soong_java_prebuilt.mk:121: error: done.
10:09:48 ckati failed with: exit status 1

#### failed to build some targets (31 seconds) ####
`

**Comment by pjgowtham** [comment]
repo sync again cos its twrp source issue.

**Comment by xxroot** [comment]
I repo sync three times with the same error
May I ask which soure you use


Thank you very much for your reply

**Comment by pjgowtham** [comment]
twrp-11, the same source that you are using. After you repo sync initially, do a repo sync --force-sync over your fully synced source.

**Comment by xxroot** [comment]
> twrp-11，与您使用的源相同。在最初进行 repo sync 后，对完全同步的源执行 repo sync --force-sync。

yes，I do the same.
repo sync --force-sync -j4

I'm using vmware ubuntu20.04

**Comment by xxroot** [comment]
thank you,successfully
I redid it several times and it worked

make clean
repo sync --force-sync -j4
